### ISSUE TITLE
Unclear which parsers capture and which don't

### ISSUE THREAD

**Issue by alexbbrown** [pointfreeco/swift-parsing#44]
I was struggling to understand when to use `Prefix` and when to use `StartsWith` - they sound very similar.  

However, my hand was forced because StartsWith appears not to capture the value.

suggestion: StartsWith (and other parsers) should clearly state if they capture or not.  

```
- A parser that parses a sequence of elements from its input.
+ A parser that matches and skips over a sequence of elements from its input.
```

Alternatively, why not make startsWith capture?  At the moment it returns Void, but it has a very handy and cheap value available to it.  This is interesting in the case of alternation.  From the example you give in the main document: 

```
let city = StartsWith<Substring>("London").map { City.london }
  .orElse(StartsWith("New York").map { .newYork })
  .orElse(StartsWith("San José").map { .sanJose })
```
works fine, but if it captured, then we get *tokenization* for free

```
let city = StartsWith<Substring>("London") // --> "London", rest
  .orElse(StartsWith("New York")) // --> "New York", rest
  .orElse(StartsWith("San José")) // --> "San José", rest
```

---
PS: this is the first issue I have raised, so feel free to tell me this isn't the kind of issue you want!

**Comment by stephencelis** [comment]
Everything could probably be spelled out more explicitly and documented more thoroughly, but we go by Swift's Collection naming conventions. So:

- `StartsWith` should remind you of `string.startsWith("London")`
- `Prefix` should remind you of `string.prefix(1)`, and `string.prefix(while: { $0.isWhitespace })`
- `PrefixUpTo` and `PrefixThrough` should remind you of `string.prefix(upTo:)` and `string.prefix(through:)`

The reason `StartsWith` doesn't "capture" any output is because the output it would parse is already known (it is literally being passed along to the parser).

`Prefix`, meanwhile, does _not_ know the output that it will parse till it runs.

By making `StartsWith`'s output `Void`, we are also given a parser whose output is ignored when used at the beginning of a chain of `skip`/`take` operations. If `StartsWith` was _not_ `Void`, it would mean introducing the extra work of `Skip()`:

```swift
StartsWith("Hello, ")
// vs.
Skip(StartsWith("Hello, "))
```

One more reason `StartsWith` does not capture is that it cannot capture and be an invertible parser. We'll be exploring this topic soon, but basically, an invertible parser can introduce a `print` function that given an output, can always "print" and input.

```swift
let parser = StartsWith("Hello")

parser.parse("Hello, world!") // ()
parser.print(()) // "Hello, world!"
```

`Void` is the perfect "output" here because the parser already knows how to invert things.

**Comment by alexbbrown** [comment]
Makes sense, thanks Stephen

**Comment by alexbbrown** [comment]
note: I would perhaps have chosen "dropPrefix" instead of "startsWith"

**Comment by stephencelis** [comment]
Thanks for the feedback! I've been taking a number of your suggestions and am attempting to improve things here: https://github.com/pointfreeco/swift-parsing/pull/45/files
